### ISSUE TITLE
list index out of range in dns_discovery.py

### ISSUE THREAD

**Issue by Jocomol** [Jocomol/NSA#9]
Traceback (most recent call last):
  File "controller.py", line 11, in <module>
    run()
  File "controller.py", line 8, in run
    run = scriptlib.runScripts(configuration)
  File "/etc/NSA/script/scriptlib.py", line 10, in runScripts
    dnsData = dnsDiscovery(conf[2])
  File "/etc/NSA/script/scriptlib.py", line 53, in dnsDiscovery
    data = dns_discovery.run(conf)
  File "/etc/NSA/script/dns_discovery.py", line 43, in run
    if len(returnarray[j]) >= 1 and returnarray[j][0] != None and returnlist[j][0] in str(inreturn):
IndexError: list index out of range

[Error happens on this line](https://github.com/Jocomol/NSA/blob/46586e680ad76b7fadd4b13542c860d9717b89cb/Network_Snapshot_Appliance/Datenbeschaffung/dns_discovery.py#L43)

**Comment by Jocomol** [comment]
not going to fix
